language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

cache:
  directories:
      - "$HOME/.composer/cache"
      - "$HOME/.php-cs-fixer"

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --diff --verbose

before_install:
  - composer self-update

install:
  - composer install
