language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=mysql
  - DB=pgsql

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - cat config.travis.$DB.ini > config.ini

script:
  - vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --diff --verbose
  - vendor/bin/phpunit

matrix:
  include:
    - php: 5.6
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 7.0
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: 7.1
      env: DB=mariadb
      addons:
        mariadb: 10.1
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
      env: DB=mysql
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge
      services:
        - postgresql
      env: DB=pgsql

  allow_failures:
    - php: hhvm

cache:
  directories:
      - "$HOME/.composer/cache"
      - "$HOME/.php-cs-fixer"
