language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

services:
  - mysql
  - postgresql

cache:
  directories:
      - "$HOME/.composer/cache"
      - "$HOME/.php-cs-fixer"

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --diff --verbose; fi;
  - cat config.travis.mysql.ini > config.ini
  - vendor/bin/phpunit
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then cat config.travis.pgsql.ini > config.ini; fi;
  - if [[ $TRAVIS_PHP_VERSION != hhvm ]]; then vendor/bin/phpunit; fi;
