language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - DB=mysql
  - DB=pgsql

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" || $TRAVIS_PHP_VERSION == "hhvm" ]]; then cat composer5.json > composer.json; else cat composer7.json > composer.json; fi;
  - composer self-update

install:
  - composer install

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - cat config.travis.$DB.ini > config.ini

script:
  - vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --diff --verbose
  - vendor/bin/phpunit

matrix:
  include:
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge
      addons:
        apt:
          packages:
            - mysql-server-5.6
            - mysql-client-core-5.6
            - mysql-client-5.6
      services:
        - mysql
      env: DB=mysql

  allow_failures:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: hhvm

cache:
  directories:
      - "$HOME/.composer/cache"
      - "$HOME/.php-cs-fixer"
