language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  - DB=mysql
  - DB=pgsql

services:
  - mysql
  - postgresql

before_install:
  - composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS cerberus_test;'
  - psql -c 'create database cerberus_test;' -U postgres

install:
  - composer install

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - cat config.travis.$DB.ini > config.ini

script:
  - vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --diff --verbose
  - vendor/bin/phpunit

cache:
  directories:
      - "$HOME/.composer/cache"
      - "$HOME/.php-cs-fixer"
