dist: xenial

language: php

php:
  - 5.6

env:
  - DB=mysql
  - DB=postgres

before_install:
  - composer self-update
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE cerberus_test;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS cerberus_test;' -u travis; fi"

install:
  - composer install

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - cat config.travis.$DB.ini > config.ini

script:
  - vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --diff --verbose
  - vendor/bin/phpunit

cache:
  directories:
      - "$HOME/.composer/cache"
      - "$HOME/.php-cs-fixer"
