language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

services:
  - mysql
  - postgresql

cache:
  directories:
      - "$HOME/.composer/cache"
      - "$HOME/.php-cs-fixer"

before_install:
  - composer self-update

install:
  - composer install

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"

script:
  - vendor/bin/php-cs-fixer fix --cache-file "$HOME/.php-cs-fixer/.php_cs.cache" --dry-run --diff --verbose
  - cat config.travis.mysql.ini > config.ini
  - phpunit
  - cat config.travis.pgsql.ini > config.ini
  - phpunit
